name = "node"
title = "Node.js"

toc_landing_pages = ["/fundamentals/authentication", "/fundamentals/crud", "/usage-examples"]

[constants]
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
